spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/cookiedemo?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver